package scaffold

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

//go:embed boilerplate
var boilerplateFS embed.FS

type Config struct {
	Title      string
	Slides     int
	OutputDir  string
	FPS        int
	CardWidth  int
	CardHeight int
}

func DefaultConfig() Config {
	return Config{
		Slides:     7,
		FPS:        30,
		CardWidth:  1080,
		CardHeight: 1350,
	}
}

func Create(cfg Config) error {
	if cfg.OutputDir == "" {
		return fmt.Errorf("output directory required")
	}

	// Copy boilerplate files
	if err := copyBoilerplate(cfg.OutputDir); err != nil {
		return fmt.Errorf("copy boilerplate: %w", err)
	}

	// Generate data.ts
	if err := generateDataTS(cfg); err != nil {
		return fmt.Errorf("generate data.ts: %w", err)
	}

	// Generate cards/index.ts
	if err := generateCardsIndex(cfg); err != nil {
		return fmt.Errorf("generate cards/index.ts: %w", err)
	}

	// Generate skeleton card components
	if err := generateSkeletonCards(cfg); err != nil {
		return fmt.Errorf("generate skeleton cards: %w", err)
	}

	// Create public/ directory for images and audio
	publicDir := filepath.Join(cfg.OutputDir, "public")
	if err := os.MkdirAll(publicDir, 0o755); err != nil {
		return fmt.Errorf("create public dir: %w", err)
	}

	return nil
}

func copyBoilerplate(destDir string) error {
	return fs.WalkDir(boilerplateFS, "boilerplate", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Strip "boilerplate/" prefix
		relPath := strings.TrimPrefix(path, "boilerplate/")
		if relPath == "" || path == "boilerplate" {
			return nil
		}

		destPath := filepath.Join(destDir, relPath)

		if d.IsDir() {
			return os.MkdirAll(destPath, 0o755)
		}

		// Skip template files that we generate ourselves
		base := filepath.Base(relPath)
		if base == "data.ts.tmpl" || base == "index.ts.tmpl" {
			return nil
		}

		data, err := boilerplateFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}

		if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
			return err
		}

		return os.WriteFile(destPath, data, 0o644)
	})
}

func generateDataTS(cfg Config) error {
	framesPerCard := cfg.FPS * 5 // 5 seconds default

	var durations []string
	for i := 0; i < cfg.Slides; i++ {
		durations = append(durations, fmt.Sprintf("%d", framesPerCard))
	}

	content := fmt.Sprintf(`// Auto-generated by mmk-cn — edit CARD_DURATIONS after TTS
export const FPS = %d;

export const CARD_COUNT = %d;
export const CARD_WIDTH = %d;
export const CARD_HEIGHT = %d;
export const VERTICAL_WIDTH = 1080;
export const VERTICAL_HEIGHT = 1920;

// Default: %d seconds per card (%d frames). Replace with TTS timings.
const ACTUAL_CARD_FRAMES = [%s];
export const TOTAL_FRAMES = ACTUAL_CARD_FRAMES.reduce((a, b) => a + b, 0);

export const CARD_DURATIONS = ACTUAL_CARD_FRAMES;

// Subtitle lines — populate after TTS script is written
export const SUBTITLE_LINES: string[][] = [
%s];

export type SubtitleSegment = {
  start: number;
  end: number;
  text: string;
};

const getTextWeight = (text: string): number => text.replace(/\s+/g, "").length;

const distributeByWeights = (total: number, weights: number[]): number[] => {
  const weightSum = weights.reduce((sum, w) => sum + w, 0);
  const raw = weights.map((w) => (w / weightSum) * total);
  const base = raw.map((v) => Math.floor(v));
  let remainder = total - base.reduce((s, v) => s + v, 0);
  const ranked = raw
    .map((v, i) => ({ index: i, fraction: v - Math.floor(v) }))
    .sort((a, b) => b.fraction - a.fraction);
  for (let i = 0; i < ranked.length && remainder > 0; i++) {
    base[ranked[i].index] += 1;
    remainder -= 1;
  }
  return base;
};

export const SUBTITLE_SEGMENTS: SubtitleSegment[] = (() => {
  const segments: SubtitleSegment[] = [];
  let cursor = 0;
  SUBTITLE_LINES.forEach((lines, cardIndex) => {
    if (lines.length === 0) {
      cursor += CARD_DURATIONS[cardIndex];
      return;
    }
    const framesPerLine = distributeByWeights(
      CARD_DURATIONS[cardIndex],
      lines.map(getTextWeight),
    );
    let localCursor = cursor;
    lines.forEach((text, lineIndex) => {
      segments.push({
        start: localCursor,
        end: localCursor + framesPerLine[lineIndex],
        text,
      });
      localCursor += framesPerLine[lineIndex];
    });
    cursor += CARD_DURATIONS[cardIndex];
  });
  return segments;
})();
`,
		cfg.FPS,
		cfg.Slides,
		cfg.CardWidth, cfg.CardHeight,
		5, framesPerCard,
		strings.Join(durations, ", "),
		generateEmptySubtitleLines(cfg.Slides),
	)

	destPath := filepath.Join(cfg.OutputDir, "src", "data.ts")
	if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(destPath, []byte(content), 0o644)
}

func generateEmptySubtitleLines(count int) string {
	var lines []string
	for i := 0; i < count; i++ {
		lines = append(lines, "  [],")
	}
	return strings.Join(lines, "\n") + "\n"
}

func generateCardsIndex(cfg Config) error {
	var imports, components, assets []string
	for i := 1; i <= cfg.Slides; i++ {
		num := fmt.Sprintf("%02d", i)
		imports = append(imports, fmt.Sprintf(`import {Card%s} from "./Card%s";`, num, num))
		components = append(components, fmt.Sprintf("  Card%s,", num))
		assets = append(assets, fmt.Sprintf(`  "card-%s.png",`, num))
	}

	content := fmt.Sprintf(`%s

export type CardComponentProps = {
  durationInFrames: number;
};

export const CARD_COMPONENTS = [
%s
];

export const CARD_ASSETS = [
%s
];
`,
		strings.Join(imports, "\n"),
		strings.Join(components, "\n"),
		strings.Join(assets, "\n"),
	)

	destPath := filepath.Join(cfg.OutputDir, "src", "cards", "index.ts")
	if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(destPath, []byte(content), 0o644)
}

func generateSkeletonCards(cfg Config) error {
	cardsDir := filepath.Join(cfg.OutputDir, "src", "cards")
	if err := os.MkdirAll(cardsDir, 0o755); err != nil {
		return err
	}

	for i := 1; i <= cfg.Slides; i++ {
		num := fmt.Sprintf("%02d", i)
		dark := i%2 == 1

		bg, textColor, subColor, pageColor := "#FAFAFA", "#0A0A0A", "rgba(0,0,0,0.6)", "rgba(0,0,0,0.3)"
		if dark {
			bg, textColor, subColor, pageColor = "#0A0A0A", "#FAFAFA", "rgba(250,250,250,0.7)", "rgba(255,255,255,0.4)"
		}

		content := fmt.Sprintf(`import React from "react";
import { AbsoluteFill, interpolate, useCurrentFrame } from "remotion";

interface CardProps {
  durationInFrames: number;
}

export const Card%s: React.FC<CardProps> = ({ durationInFrames }) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 9], [0, 1], { extrapolateRight: "clamp" });
  const fadeOut = interpolate(frame, [durationInFrames - 15, durationInFrames], [1, 0], { extrapolateLeft: "clamp" });

  return (
    <AbsoluteFill
      style={{
        background: "%s",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: "0 80px",
        opacity: fadeOut,
      }}
    >
      <h2
        style={{
          fontFamily: "'Noto Serif KR', serif",
          fontSize: 48,
          fontWeight: 900,
          color: "%s",
          textAlign: "center",
          opacity,
          lineHeight: 1.25,
        }}
      >
        {/* TODO: Card %d title */}
        카드 %d 제목
      </h2>
      <p
        style={{
          fontSize: 36,
          color: "%s",
          textAlign: "center",
          marginTop: 32,
          opacity,
          lineHeight: 1.55,
        }}
      >
        {/* TODO: Card %d body */}
        설명 텍스트
      </p>
      <div
        style={{
          position: "absolute",
          bottom: 40,
          left: "50%%",
          transform: "translateX(-50%%)",
          fontSize: 28,
          fontWeight: 300,
          letterSpacing: 3,
          color: "%s",
        }}
      >
        %d / %d
      </div>
    </AbsoluteFill>
  );
};
`, num, bg, textColor, i, i, subColor, i, pageColor, i, cfg.Slides)

		destPath := filepath.Join(cardsDir, fmt.Sprintf("Card%s.tsx", num))
		if err := os.WriteFile(destPath, []byte(content), 0o644); err != nil {
			return err
		}
	}

	return nil
}
